# Generated by Django 4.2.14 on 2024-12-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=51)),
                ('dlnumber_1', models.CharField(max_length=13)),
                ('dlnumber_2', models.CharField(max_length=13)),
                ('dlnumber_3', models.CharField(max_length=13)),
                ('dlnumber_4', models.CharField(max_length=13)),
                ('dlnumber_5', models.CharField(max_length=13)),
                ('dlnumber_6', models.CharField(max_length=13)),
                ('dlnumber_7', models.CharField(max_length=13)),
                ('dlnumber_8', models.CharField(max_length=13)),
                ('dlnumber_9', models.CharField(max_length=13)),
            ],
        ),
    ]
