# Generated by Django 4.2.14 on 2025-01-01 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=51)),
                ('dl1', models.CharField(max_length=13, unique=True)),
                ('dl2', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalDLNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_number', models.CharField(max_length=13, unique=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_dl_numbers', to='mediprofile.section1')),
            ],
        ),
    ]
