# Generated by Django 4.2.14 on 2025-01-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(choices=[('Proprietorship', 'Proprietorship'), ('Partnership', 'Partnership'), ('Private Limited', 'Private Limited'), ('LLP', 'LLP'), ('Franchise', 'Franchise'), ('Cooperative Society', 'Cooperative Society')], max_length=50)),
                ('business_name', models.CharField(max_length=100)),
                ('pan', models.CharField(blank=True, max_length=10, null=True)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('proprietor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('partnership_name', models.CharField(blank=True, max_length=100, null=True)),
                ('partners', models.JSONField(blank=True, null=True)),
                ('cin', models.CharField(blank=True, max_length=21, null=True)),
                ('directors', models.JSONField(blank=True, null=True)),
                ('llpin', models.CharField(blank=True, max_length=7, null=True)),
                ('franchise_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('franchise_agreement_number', models.CharField(blank=True, max_length=50, null=True)),
                ('franchise_duration', models.IntegerField(blank=True, null=True)),
                ('parent_company_representative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('parent_company_representative_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('society_name', models.CharField(blank=True, max_length=100, null=True)),
                ('members', models.JSONField(blank=True, null=True)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('registered_address', models.TextField()),
                ('shop_address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
